export const AUTH_USER = 'AUTH_USER'; 
export const DEAUTH_USER = 'DEAUTH_USER'; 
export const AUTH_ERROR = 'AUTH_ERROR';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_ERROR = 'FETCH_ERROR';

export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';

